package com.xworkz.examples;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;

public class DamsList {
	
	public static void main(String[] args) {
		
		Collection<String> damsInArunachalPradesh=new ArrayList<String>();
		damsInArunachalPradesh.add("Ranganadi");
		damsInArunachalPradesh.add("Subansiri Lower HE");
		System.out.println("Size of dams in Arunachal Pradesh : "+damsInArunachalPradesh.size());
		
		Collection<String> damsInNagaland=new ArrayList<String>();
		damsInNagaland.add("Hep");
		System.out.println("Size of dams in Nagaland : "+damsInNagaland.size());
		
		Collection<String> damsInManipur=new ArrayList<String>();
		damsInManipur.add("Khoupum");
		damsInManipur.add("Khuga");
		damsInManipur.add("Singda");
		damsInManipur.add("Thoubal");
		System.out.println("Size of dams in Manipur : "+damsInManipur.size());
		
		Collection<String> damsInMizoram=new ArrayList<String>();
		damsInMizoram.add("Serlui B");
		damsInMizoram.add("Tuirial");
		System.out.println("Size of dams in Mizoram : "+damsInMizoram.size());
		
		Collection<String> damsInAssam=new ArrayList<String>();
		damsInAssam.add("Karbi Langpi");
		damsInAssam.add("Umrong");
		System.out.println("Size of dams in Assam : "+damsInAssam.size());
		
		Collection<String> damsInMeghalaya=new ArrayList<String>();
		damsInMeghalaya.add("Khandong");
		damsInMeghalaya.add("Kyrdemkulai");
		damsInMeghalaya.add("Mawphlang");
		damsInMeghalaya.add("Myntdu-Leshka");
		damsInMeghalaya.add("Nongkhyllem");
		damsInMeghalaya.add("Umiam");
		damsInMeghalaya.add("Umtru");
		System.out.println("Size of dams in Meghalaya : "+damsInMeghalaya.size());
		
		Collection<String> damsInTripura=new ArrayList<String>();
		damsInTripura.add("Gumti Hydro");
		System.out.println("Size of dams in Tripura : "+damsInTripura.size());
		
		Collection<String> damsInWestBengal=new ArrayList<String>();
		damsInWestBengal.add("Bakreshwar");
		damsInWestBengal.add("Bandhu");
		damsInWestBengal.add("Bara Mandira");
		damsInWestBengal.add("Barabhum");
		damsInWestBengal.add("Beko");
		damsInWestBengal.add("Dangrajhore");
		damsInWestBengal.add("Dimu");
		damsInWestBengal.add("Futiary");
		damsInWestBengal.add("Golamarajore");
		damsInWestBengal.add("Hanumata");
		damsInWestBengal.add("Hinglow Irrigation Scheme");
		damsInWestBengal.add("Kangsabati Kumari");
		damsInWestBengal.add("Kanjan");
		damsInWestBengal.add("Karrior");
		damsInWestBengal.add("Khairabera");
		damsInWestBengal.add("Kumari");
		damsInWestBengal.add("Lipania");
		damsInWestBengal.add("Lower : PPSP");
		damsInWestBengal.add("Moutorejore");
		damsInWestBengal.add("Muruguma");
		damsInWestBengal.add("Nachan Irri Scheme");
		damsInWestBengal.add("Paraga Irri. Scheme");
		damsInWestBengal.add("Patloi");
		damsInWestBengal.add("Ramchandrapur");
		damsInWestBengal.add("Rupai");
		damsInWestBengal.add("Saharajore Irri Scheme");
		damsInWestBengal.add("Sali");
		damsInWestBengal.add("Taragonia Irri Scheme");
		damsInWestBengal.add("Tatko");
		damsInWestBengal.add("Teesta-III Lower");
		damsInWestBengal.add("Teesta-IV Lower");
		damsInWestBengal.add("Turga Irri Scheme");
		damsInWestBengal.add("Upper Dam: PPSP");
		System.out.println("Size of dams in WestBengal : "+damsInWestBengal.size());
		
		Collection<String> damsInSikkim=new ArrayList<String>();
		damsInSikkim.add("Rangit III");
		damsInSikkim.add("Rangpo");
		damsInSikkim.add("Rongli");
		damsInSikkim.add("Teesta -V (NHPC)");
		damsInSikkim.add("Teesta-III");
		damsInSikkim.add("Teesta-IV");
		System.out.println("Size of dams in Sikkim : "+damsInSikkim.size());
		
		Collection<String> damsInBihar=new ArrayList<String>();
		damsInBihar.add("Ajan");
		damsInBihar.add("Amrity");
		damsInBihar.add("Badua");
		damsInBihar.add("Barnar");
		damsInBihar.add("Baskund");
		damsInBihar.add("Belharna");
		damsInBihar.add("Bilasi");
		damsInBihar.add("Chandan");
		damsInBihar.add("Durgawati");
		damsInBihar.add("Gaighat");
		damsInBihar.add("Jalkund");
		damsInBihar.add("Job");
		damsInBihar.add("Kailash Ghati");
		damsInBihar.add("Khargpur Lake");
		damsInBihar.add("Kohira");
		damsInBihar.add("Kolmahadeo");
		damsInBihar.add("Morwy");
		damsInBihar.add("Nagi");
		damsInBihar.add("Nakti");
		damsInBihar.add("Orhni");
		damsInBihar.add("Phulwaria");
		damsInBihar.add("Sindhwarni");
		damsInBihar.add("Srikhandi");
		damsInBihar.add("Upper Kiul");
		System.out.println("Size of dams in Bihar : "+damsInBihar.size());
		
		Collection<String> damsInJharkhand=new ArrayList<String>();
		damsInJharkhand.add("Amanat");
		damsInJharkhand.add("Anjanwa");
		damsInJharkhand.add("Anraj");
		damsInJharkhand.add("Baksa");
		damsInJharkhand.add("Bandha");
		damsInJharkhand.add("Baranadi");
		damsInJharkhand.add("Barhi");
		damsInJharkhand.add("Basuki");
		damsInJharkhand.add("Batane");
		damsInJharkhand.add("Batre");
		damsInJharkhand.add("Bhairwa");
		damsInJharkhand.add("Bhavnikhand Khand");
		damsInJharkhand.add("Bhutanduba");
		damsInJharkhand.add("Bucha Opa");
		damsInJharkhand.add("Burhai");
		damsInJharkhand.add("Chandil");
		damsInJharkhand.add("Chatania Ghat");
		damsInJharkhand.add("Chinda");
		damsInJharkhand.add("Chirka");
		damsInJharkhand.add("Danro");
		damsInJharkhand.add("Dhankai");
		damsInJharkhand.add("Dhansingtoli");
		damsInJharkhand.add("Dhulki");
		damsInJharkhand.add("Diggalpahari");
		damsInJharkhand.add("Garhi");
		damsInJharkhand.add("Getalsud");
		damsInJharkhand.add("Ghaghra");
		damsInJharkhand.add("Gonda");
		damsInJharkhand.add("Hatia");
		damsInJharkhand.add("Hiru");
		damsInJharkhand.add("Icha");
		damsInJharkhand.add("Jaipur");
		damsInJharkhand.add("Jamunia");
		damsInJharkhand.add("Jenasai");
		damsInJharkhand.add("Jharjhara");
		damsInJharkhand.add("Kanhar");
		damsInJharkhand.add("Kans");
		damsInJharkhand.add("Kansjore");
		damsInJharkhand.add("Karawani");
		damsInJharkhand.add("Katri");
		damsInJharkhand.add("Kesho");
		damsInJharkhand.add("Khudia");
		damsInJharkhand.add("Konar");
		damsInJharkhand.add("Larwa");
		damsInJharkhand.add("Latratu");
		damsInJharkhand.add("Left Banki");
		damsInJharkhand.add("Lorgara");
		damsInJharkhand.add("Lotia");
		damsInJharkhand.add("Maithon");
		damsInJharkhand.add("Malay");
		damsInJharkhand.add("Masanjor JH");
		damsInJharkhand.add("Masaria");
		damsInJharkhand.add("Murahir");
		damsInJharkhand.add("Nakti");
		damsInJharkhand.add("Nalkari");
		damsInJharkhand.add("Nandini");
		damsInJharkhand.add("North Koel");
		damsInJharkhand.add("Palna");
		damsInJharkhand.add("Panchat Hill");
		damsInJharkhand.add("Panchkhero");
		damsInJharkhand.add("Pandarwa");
		damsInJharkhand.add("Paras");
		damsInJharkhand.add("Punasi");
		damsInJharkhand.add("Raisa");
		damsInJharkhand.add("Ramrekha");
		damsInJharkhand.add("Salaiya");
		damsInJharkhand.add("Satpotka");
		damsInJharkhand.add("Sitaram Pur");
		damsInJharkhand.add("Sonua");
		damsInJharkhand.add("Sudhari Nala");
		damsInJharkhand.add("Sugathan");
		damsInJharkhand.add("Sukri");
		damsInJharkhand.add("Sunder");
		damsInJharkhand.add("Surangi");
		damsInJharkhand.add("Suryodi");
		damsInJharkhand.add("Tahlay");
		damsInJharkhand.add("Tajna");
		damsInJharkhand.add("Tapkara");
		damsInJharkhand.add("Temrain");
		damsInJharkhand.add("Tenughat");
		damsInJharkhand.add("Tilaiya");
		damsInJharkhand.add("Torai");
		damsInJharkhand.add("Torlow");
		damsInJharkhand.add("Upper Shankh");
		System.out.println("Size of dams in Jharkhand : "+damsInJharkhand.size());
		
		Collection<String> damsInOdisha=new ArrayList<String>();
		damsInOdisha.add("Alubani");
		damsInOdisha.add("Aradei");
		damsInOdisha.add("Arikul");
		damsInOdisha.add("Badabandha");
		damsInOdisha.add("Badanalla");
		damsInOdisha.add("Badjore");
		damsInOdisha.add("Baghalati");
		damsInOdisha.add("Baghjharan");
		damsInOdisha.add("Baghua");
		damsInOdisha.add("Baghua (MI)");
		damsInOdisha.add("Balaskumpa");
		damsInOdisha.add("Balimela");
		damsInOdisha.add("Bankabal");
		damsInOdisha.add("Banksal");
		damsInOdisha.add("Baura");
		damsInOdisha.add("Bautia");
		damsInOdisha.add("Bedapada");
		damsInOdisha.add("Behera");
		damsInOdisha.add("Benikpur");
		damsInOdisha.add("Bhagirijhala");
		damsInOdisha.add("Bhallugahi");
		damsInOdisha.add("Bhaluguda");
		damsInOdisha.add("Bhanjanagar");
		damsInOdisha.add("Bhaskel");
		damsInOdisha.add("Bhatrajore");
		damsInOdisha.add("Bhetabar");
		damsInOdisha.add("Bhitiri Bediguda");
		damsInOdisha.add("Budhabudiani");
		damsInOdisha.add("Chhamundia");
		damsInOdisha.add("Chhatenjore");
		damsInOdisha.add("Chheligada");
		damsInOdisha.add("Dadara Ghati");
		damsInOdisha.add("Daha(OD)");
		damsInOdisha.add("Damsal");
		damsInOdisha.add("Dasamanthapur");
		damsInOdisha.add("Debijharan");
		damsInOdisha.add("Deo(OD)");
		damsInOdisha.add("Deojharan");
		damsInOdisha.add("Deras");
		damsInOdisha.add("Derjang");
		damsInOdisha.add("Dhanei");
		damsInOdisha.add("Dhulipaunsia");
		damsInOdisha.add("Domkutch");
		damsInOdisha.add("Dumerbahal");
		damsInOdisha.add("Gaikhai(Minor)");
		damsInOdisha.add("Ganianalla");
		damsInOdisha.add("Garh");
		damsInOdisha.add("Gayapathar");
		damsInOdisha.add("Ghagara");
		damsInOdisha.add("Ghatakeswar");
		damsInOdisha.add("Ghodahada");
		damsInOdisha.add("Gohira");
		damsInOdisha.add("Goibali");
		damsInOdisha.add("Gundurapasi");
		damsInOdisha.add("Gurlijore");
		damsInOdisha.add("HATIANALLA M.I.P");
		damsInOdisha.add("Hadua");
		damsInOdisha.add("Haguri");
		damsInOdisha.add("Haladia");
		damsInOdisha.add("Hanumantia");
		damsInOdisha.add("Harabhangi");
		damsInOdisha.add("Hariharjore");
		damsInOdisha.add("Haripur");
		damsInOdisha.add("Hirakud");
		damsInOdisha.add("Indrawati");
		damsInOdisha.add("Jagadala");
		damsInOdisha.add("Jaigarh");
		damsInOdisha.add("Jalaput");
		damsInOdisha.add("Jambhira");
		damsInOdisha.add("Jamboonala");
		damsInOdisha.add("Jamuna Bundha");
		damsInOdisha.add("Jaunria");
		damsInOdisha.add("Jharanai");
		damsInOdisha.add("Jharbandha");
		damsInOdisha.add("Jhumuka");
		damsInOdisha.add("Jodabadia");
		damsInOdisha.add("Kakudajodi");
		damsInOdisha.add("Kalakala");
		damsInOdisha.add("Kalijodi");
		damsInOdisha.add("Kalo");
		damsInOdisha.add("Kangani");
		damsInOdisha.add("Kanheinalla");
		damsInOdisha.add("Kanjhari");
		damsInOdisha.add("Kansabansa");
		damsInOdisha.add("Kansbahal");
		damsInOdisha.add("Kanteijhara");
		damsInOdisha.add("Kantesir");
		damsInOdisha.add("Kanupur");
		damsInOdisha.add("Kapur");
		damsInOdisha.add("Karada");
		damsInOdisha.add("Karanjkote");
		damsInOdisha.add("Khadakhai");
		damsInOdisha.add("Khajuria");
		damsInOdisha.add("Khandijharan");
		damsInOdisha.add("Khasbahal");
		damsInOdisha.add("Khuntapada");
		damsInOdisha.add("Kiajhar");
		damsInOdisha.add("Kodabhal");
		damsInOdisha.add("Kodigam");
		damsInOdisha.add("Konheimunda");
		damsInOdisha.add("Koska");
		damsInOdisha.add("Kuanria");
		damsInOdisha.add("Kukurpeta");
		damsInOdisha.add("Kumbho");
		damsInOdisha.add("Kureijodi");
		damsInOdisha.add("Kusunpur");
		damsInOdisha.add("Laigam");
		damsInOdisha.add("Lakhaparbat");
		damsInOdisha.add("Laupal");
		damsInOdisha.add("Laxmipur");
		damsInOdisha.add("Liar");
		damsInOdisha.add("Lower Indra");
		damsInOdisha.add("Lower Suktal");
		damsInOdisha.add("Magara");
		damsInOdisha.add("Maharanisagar");
		damsInOdisha.add("Mahendratanaya");
		damsInOdisha.add("Mahisanalla");
		damsInOdisha.add("Malakangiri");
		damsInOdisha.add("Mandira");
		damsInOdisha.add("Manjhor");
		damsInOdisha.add("Marudi");
		damsInOdisha.add("Masina");
		damsInOdisha.add("Mathan Pal");
		damsInOdisha.add("Mathili");
		damsInOdisha.add("Muran");
		damsInOdisha.add("Nesa");
		damsInOdisha.add("Nimajhar Mip");
		damsInOdisha.add("Padampur");
		damsInOdisha.add("Paitagam");
		damsInOdisha.add("Panaskhal");
		damsInOdisha.add("Pani-Pailla");
		damsInOdisha.add("Pansapal");
		damsInOdisha.add("Parhal");
		damsInOdisha.add("Paunsia");
		damsInOdisha.add("Pilasalki");
		damsInOdisha.add("Pipal");
		damsInOdisha.add("Pitamahal");
		damsInOdisha.add("Podagada");
		damsInOdisha.add("Pokharia");
		damsInOdisha.add("Pratappur");
		damsInOdisha.add("Pujiladu");
		damsInOdisha.add("Raghubeda");
		damsInOdisha.add("Raghunath Sagar");
		damsInOdisha.add("Raijharan");
		damsInOdisha.add("Ramaguda");
		damsInOdisha.add("Ramiala");
		damsInOdisha.add("Randa");
		damsInOdisha.add("Remal");
		damsInOdisha.add("Rengali");
		damsInOdisha.add("Ret");
		damsInOdisha.add("Rissia");
		damsInOdisha.add("Rukura");
		damsInOdisha.add("Rungaon");
		damsInOdisha.add("Saipala");
		damsInOdisha.add("Salandi");
		damsInOdisha.add("Salia");
		damsInOdisha.add("Sanasialinai");
		damsInOdisha.add("Sanmachhakandana");
		damsInOdisha.add("Sapua");
		damsInOdisha.add("Sarapa");
		damsInOdisha.add("Saraphgarh");
		damsInOdisha.add("Satiguda");
		damsInOdisha.add("Sendhie");
		damsInOdisha.add("Soroda");
		damsInOdisha.add("Suhagi");
		damsInOdisha.add("Sunaghai");
		damsInOdisha.add("Sunamuhin");
		damsInOdisha.add("Sundar");
		damsInOdisha.add("Sunei");
		damsInOdisha.add("Talasara");
		damsInOdisha.add("Talkhol");
		damsInOdisha.add("Tangarakana");
		damsInOdisha.add("Telengiri");
		damsInOdisha.add("Tenar");
		damsInOdisha.add("Tikarpada");
		damsInOdisha.add("Tilipada");
		damsInOdisha.add("Titilagarh");
		damsInOdisha.add("Upper Jonk");
		damsInOdisha.add("Upper Kolab");
		damsInOdisha.add("Upper Lanth");
		damsInOdisha.add("Upper Suktel");
		System.out.println("Size of dams in Odisha : "+damsInOdisha.size());
	
		Collection<String> damsInKarnataka = new ArrayList<String>();
		damsInKarnataka.add("Almatti");
		damsInKarnataka.add("Basava Sagara");
		damsInKarnataka.add("Raja Lakhamagowda");
		damsInKarnataka.add("Renuka Sagara");
		damsInKarnataka.add("Vani Vilasa Sagara");
		damsInKarnataka.add("Upper Tunga");
		damsInKarnataka.add("Bhadra");
		damsInKarnataka.add("Tungabhadra");
		damsInKarnataka.add("Hemavathi Reservoir");
		damsInKarnataka.add("Kabini Reservoir");
		damsInKarnataka.add("Harangi Reservoir");
		damsInKarnataka.add("Krishna Raja Sagara");
		damsInKarnataka.add("Linganamakki");
		damsInKarnataka.add("Chakra Reservoir");
		damsInKarnataka.add("Savehaklu Reservoir");
		damsInKarnataka.add("Mani Reservoir");
		damsInKarnataka.add("Supa");
		damsInKarnataka.add("Kodasalli");
		damsInKarnataka.add("Kadra");
		damsInKarnataka.add("Shanti Sagara");
		damsInKarnataka.add("Karanja");
		System.out.println("Size of dams in Karnataka : "+damsInKarnataka.size());
		
		
		Collection<String> damsInKerala = new ArrayList<String>();
		damsInKerala.add("Banasura Sagar");
		damsInKerala.add("Mattupetty");
		damsInKerala.add("Idukki");
		damsInKerala.add("Malampuzha Garden and Dam");
		damsInKerala.add("Maniyar");
		damsInKerala.add("Walayar");
		damsInKerala.add("Anathode");
		damsInKerala.add("Anayirangal");
		damsInKerala.add("Aruvikkara");
		damsInKerala.add("Azhutha");
		damsInKerala.add("Bhoothathankettu");
		damsInKerala.add("Chulliyar");
		damsInKerala.add("Chenkulam");
		damsInKerala.add("Cheruthoni");
		damsInKerala.add("Chimmini");
		damsInKerala.add("Erattayar");
		damsInKerala.add("Gavi");
		damsInKerala.add("Idamalayar");
		damsInKerala.add("Kakki");
		damsInKerala.add("Kakkad");
		damsInKerala.add("Kakkayam");
		damsInKerala.add("Kallar");
		damsInKerala.add("Kanjirapuzha");
		damsInKerala.add("Karapuzha");
		damsInKerala.add("Kochu Pamba");
		damsInKerala.add("Kulamavu");
		damsInKerala.add("Kullar");
		damsInKerala.add("Kallarkutty");
		damsInKerala.add("KundalaPambla");
		damsInKerala.add("Ranni-Perinad");
		damsInKerala.add("Mangalam");
		damsInKerala.add("Malampuzha");
		damsInKerala.add("Malankara");
		damsInKerala.add("Mattupetty");
		damsInKerala.add("Meenar -1");
		damsInKerala.add("Meenar -2");
		damsInKerala.add("Meenkara");
		damsInKerala.add("Mullaperiyar");
		damsInKerala.add("Mullakkanam");
		damsInKerala.add("Moozhiyar");
		damsInKerala.add("Narakakkanam");
		damsInKerala.add("Neyyar");
		damsInKerala.add("Pamba");
		damsInKerala.add("Pambla");
		damsInKerala.add("Parakkadavu");
		damsInKerala.add("Pazhassi");
		damsInKerala.add("Peppara");
		damsInKerala.add("Peringalkuthu");
		damsInKerala.add("Perunthenaruvi");
		damsInKerala.add("Peruvannamuzhi");
		damsInKerala.add("Peruvaripallam");
		damsInKerala.add("Peechi");
		damsInKerala.add("Parambikulam");
		damsInKerala.add("Ponmudi");
		damsInKerala.add("Pothundi");
		damsInKerala.add("R. A. Headworks");
		damsInKerala.add("Upper Moozhiyar");
		damsInKerala.add("Sholayar");
		damsInKerala.add("Siruvani");
		damsInKerala.add("Thoonakkadavu");
		damsInKerala.add("Thenmala");
		damsInKerala.add("Urumi 1");
		damsInKerala.add("Urumi 2");
		damsInKerala.add("Vazhani");
		damsInKerala.add("Vellathooval");
		damsInKerala.add("Veluthodu");
		damsInKerala.add("Viripara");
		System.out.println("Size of dams in Kerala : "+damsInKerala.size());
		

		Collection<String> damsInTamilNadu = new ArrayList<String>();
		damsInTamilNadu.add("Aathupalayam");
		damsInTamilNadu.add("Adavinainar");
		damsInTamilNadu.add("Aliyar Reservoir");
		damsInTamilNadu.add("Amaravathi");
		damsInTamilNadu.add("Anaikuttam");
		damsInTamilNadu.add("Bhavanisagar");
		damsInTamilNadu.add("Gomukhinadhi Reservoir");
		damsInTamilNadu.add("Kalingarayan Anicut");
		damsInTamilNadu.add("Kallanai");
		damsInTamilNadu.add("Kamaraj Sagar");
		damsInTamilNadu.add("Karuppanadhi");
		damsInTamilNadu.add("Kodaganar");
		damsInTamilNadu.add("Kodiveri");
		damsInTamilNadu.add("Krishnagiri");
		damsInTamilNadu.add("Kunderipallam");
		damsInTamilNadu.add("Kuppanatham");
		damsInTamilNadu.add("Lower Anaicut");
		damsInTamilNadu.add("Manimuthar");
		damsInTamilNadu.add("Manjalar");
		damsInTamilNadu.add("Mettur");
		damsInTamilNadu.add("Mukkadal");
		damsInTamilNadu.add("Nallathangal");
		damsInTamilNadu.add("Orathuppalayam");
		damsInTamilNadu.add("Papanasam");
		damsInTamilNadu.add("Pechiparai Reservoir");
		damsInTamilNadu.add("Perumpallam");
		damsInTamilNadu.add("Perunchani");
		damsInTamilNadu.add("Poigai");
		damsInTamilNadu.add("Sathanur");
		damsInTamilNadu.add("Servalar");
		damsInTamilNadu.add("Shanmuganathi");
		damsInTamilNadu.add("Solaiyar");
		damsInTamilNadu.add("Sothuparai");
		damsInTamilNadu.add("Thirumoorthy");
		damsInTamilNadu.add("Upper Anaicut");
		damsInTamilNadu.add("Vaigai");
		damsInTamilNadu.add("Varattupallam");
		System.out.println("Size of dams in TamilNadu : "+damsInTamilNadu.size());
		
		Collection<String> damsInAndhraPradesh = new ArrayList<String>();
		damsInAndhraPradesh.add("Ahobilam / Penna Ahobilam (Dr. K.S.P.A.B.R.) Dam");
		damsInAndhraPradesh.add("Akkapalem");
		damsInAndhraPradesh.add("Alaganoor");
		damsInAndhraPradesh.add("Ananthasagarm");
		damsInAndhraPradesh.add("Andhra");
		damsInAndhraPradesh.add("Arniar");
		damsInAndhraPradesh.add("Bahuda");
		damsInAndhraPradesh.add("Bhairavanithippa");
		damsInAndhraPradesh.add("Bhupathipalem");
		damsInAndhraPradesh.add("Buggavagu");
		damsInAndhraPradesh.add("Buggavanka");
		damsInAndhraPradesh.add("Bukkapatnam");
		damsInAndhraPradesh.add("Chagallu Barrage");
		damsInAndhraPradesh.add("Cheyyeru / Annamayya");
		damsInAndhraPradesh.add("Chinnarayaswamy Gudi /Chennaraya");
		damsInAndhraPradesh.add("Chintakuntavagu");
		damsInAndhraPradesh.add("Chitravathi");
		damsInAndhraPradesh.add("Cumbum");
		damsInAndhraPradesh.add("Dharmavaram");
		damsInAndhraPradesh.add("Donkarai ( S.H.E.S)");
		damsInAndhraPradesh.add("Eguva Thamballa Palli - Cheruvu");
		damsInAndhraPradesh.add("Forebay Lower Sileru ( S.H.E.S)");
		damsInAndhraPradesh.add("Gajuladinne (Sanjeevaiah Sagar)");
		damsInAndhraPradesh.add("Gandicheruvu (Dist-Prakasam)");
		damsInAndhraPradesh.add("Gandipalem /Pcr Gandipalem");
		damsInAndhraPradesh.add("Ghambiramgedda");
		damsInAndhraPradesh.add("Gooty Tank");
		damsInAndhraPradesh.add("Gorakallu");
		damsInAndhraPradesh.add("Gundlakamma");
		damsInAndhraPradesh.add("Gundlamotu");
		damsInAndhraPradesh.add("Guntawada Main");
		damsInAndhraPradesh.add("Haresamudram Big");
		damsInAndhraPradesh.add("Hiramandalam");
		damsInAndhraPradesh.add("Jajigedda");
		damsInAndhraPradesh.add("Jalakanur");
		damsInAndhraPradesh.add("Jalleru");
		damsInAndhraPradesh.add("Janjavathi");
		damsInAndhraPradesh.add("Kakarla");
		damsInAndhraPradesh.add("Kalangi");
		damsInAndhraPradesh.add("Kalyani");
		damsInAndhraPradesh.add("Kampasamudram New");
		damsInAndhraPradesh.add("Kandaleru");
		damsInAndhraPradesh.add("Kanigiri");
		damsInAndhraPradesh.add("Konam");
		damsInAndhraPradesh.add("Kovvadakalva");
		damsInAndhraPradesh.add("Kumili");
		damsInAndhraPradesh.add("Kushavathi");
		damsInAndhraPradesh.add("Lower Sagileru");
		damsInAndhraPradesh.add("Madakasira");
		damsInAndhraPradesh.add("Maddigedda");
		damsInAndhraPradesh.add("Madduvalasa");
		damsInAndhraPradesh.add("Mallimadugu");
		damsInAndhraPradesh.add("Mid-Pennar");
		damsInAndhraPradesh.add("Mopadu");
		damsInAndhraPradesh.add("Mararipalli");
		damsInAndhraPradesh.add("Mylavaram");
		damsInAndhraPradesh.add("Nakkalagandi");
		damsInAndhraPradesh.add("Narayanapuram");
		damsInAndhraPradesh.add("Nellore");
		damsInAndhraPradesh.add("Paleru ,Owk");
		damsInAndhraPradesh.add("Pampa");
		damsInAndhraPradesh.add("Peddabadava, Tulasikrishan");
		damsInAndhraPradesh.add("Pincha");
		damsInAndhraPradesh.add("Pittakayagulla");
		damsInAndhraPradesh.add("Polavaram");
		damsInAndhraPradesh.add("Raiwada");
		damsInAndhraPradesh.add("Rallapadu");
		damsInAndhraPradesh.add("SPVBS");
		damsInAndhraPradesh.add("Sadasivakona");
		damsInAndhraPradesh.add("Siddalagandi");
		damsInAndhraPradesh.add("Surampalem");
		damsInAndhraPradesh.add("Thammileru");
		damsInAndhraPradesh.add("Thatipudi");
		damsInAndhraPradesh.add("Upper Pennar");
		damsInAndhraPradesh.add("Velugodu");
		damsInAndhraPradesh.add("Veligonda");
		damsInAndhraPradesh.add("Vengalaraya Sagar");
		damsInAndhraPradesh.add("Vottigadda");
		damsInAndhraPradesh.add("Vanaka Badigedda");
		damsInAndhraPradesh.add("Yeddula Eswaraiah GandiKoata");
		damsInAndhraPradesh.add("Yeleru");
		damsInAndhraPradesh.add("Yerrakalva");
		damsInAndhraPradesh.add("Yogivemana");
		damsInAndhraPradesh.add("Zurreru");
		System.out.println("Size of dams in AndhraPradesh : "+damsInAndhraPradesh.size());
		
		Collection<String> damsInTelangana = new ArrayList<String>();
		damsInTelangana.add("Ada Village - Peddavagu");
		damsInTelangana.add("Akkampalli");
		damsInTelangana.add("Bandlavagu, Kukkalgudur");
		damsInTelangana.add("Bazarthathnur");
		damsInTelangana.add("Bethampudi");
		damsInTelangana.add("Bheemanpally");
		damsInTelangana.add("Boath");
		damsInTelangana.add("Boggulavagu");
		damsInTelangana.add("Chelamelavagu");
		damsInTelangana.add("Choutaplly Hanuman Reddy Lift");
		damsInTelangana.add("Dantakani Cheruvu");
		damsInTelangana.add("Devathlacheru, Yeldurthy");
		damsInTelangana.add("Dindi");
		damsInTelangana.add("Fox Sagar, Jeedimetla ");
		damsInTelangana.add("Gidda Cheru, Yellareddypet (V)");
		damsInTelangana.add("Gudipalligattu");
		damsInTelangana.add("Gujjulavagu , Gandhari ");
		damsInTelangana.add("Gundetivagu Cheroo, Reddygudem(V)");
		damsInTelangana.add("Gundlavagu");
		damsInTelangana.add("Himayat Sagar");
		damsInTelangana.add("Indirammasagar, Anajpur");
		damsInTelangana.add("Jutepally");
		damsInTelangana.add("Kaddam (K.N.R.)");
		damsInTelangana.add("Kesavari Samudram");
		damsInTelangana.add("Kinnerasani");
		damsInTelangana.add("Koil Sagar");
		damsInTelangana.add("Komaram Bheem");
		damsInTelangana.add("Komsettipally");
		damsInTelangana.add("Kothacheru");
		damsInTelangana.add("Kotipally Vagu");
		damsInTelangana.add("Lakhnapur");
		damsInTelangana.add("Lakhnavaram");
		damsInTelangana.add("Lankasagar");
		damsInTelangana.add("Adloor Yellareddy");
		damsInTelangana.add("Bibipet");
		damsInTelangana.add("Brahmanpally");
		damsInTelangana.add("Dharmaraopet");
		damsInTelangana.add("Garepally(V), Sultanabad(M)");
		damsInTelangana.add("Garla");
		damsInTelangana.add("Husnabad");
		damsInTelangana.add("Indalwai(V)");
		damsInTelangana.add("Jangampally");
		damsInTelangana.add("Kachapur");
		damsInTelangana.add("Malikacheru, Mamdabad");
		damsInTelangana.add("Mallammacheruvu Saralnagar");
		damsInTelangana.add("Malluruvagu");
		damsInTelangana.add("Medi Cheru");
		damsInTelangana.add("Mid Manair");
		damsInTelangana.add("Mukkamamidi");
		damsInTelangana.add("Mulavagu");
		damsInTelangana.add("Nagarjuna Sagar");
		damsInTelangana.add("Musi");
		damsInTelangana.add("Nagarjunasagar Tai");
		damsInTelangana.add("Nallacheru, Irvin");
		damsInTelangana.add("Nallavagu");
		damsInTelangana.add("Namaz Cheru, Gambhiraopet (V)");
		damsInTelangana.add("Nandivagu , Kasula");
		damsInTelangana.add("Neelwai");
		damsInTelangana.add("New , Bellempally");
		damsInTelangana.add("Kothur Dam");
		damsInTelangana.add("Nizam Sagar");
		damsInTelangana.add("Ookachettivagu");
		damsInTelangana.add("Oora Cheru,Yadaram");
		damsInTelangana.add("Osman Sagar");
		damsInTelangana.add("Palair");
		damsInTelangana.add("Palemvagu");
		damsInTelangana.add("Pedda Cheru");
		damsInTelangana.add("Peddarayanicheru");
		damsInTelangana.add("Peddavagu-Jagannathpur");
		damsInTelangana.add("Pocharam");
		damsInTelangana.add("Priyadarshini Jurala");
		damsInTelangana.add("Rai Rao Cheru");
		damsInTelangana.add("Ramadugu");
		damsInTelangana.add("Ramappa");
		damsInTelangana.add("Salivagu");
		damsInTelangana.add("Sangambanda");
		damsInTelangana.add("Sarala Sagar");
		damsInTelangana.add("Sathanala");
		damsInTelangana.add("Shanigram");
		damsInTelangana.add("Singhabhoopalem");
		damsInTelangana.add("Singur");
		damsInTelangana.add("Pochampad");
		damsInTelangana.add("Srisailam (N.S.R.S.P)");
		damsInTelangana.add("Suryanarayanacheru");
		damsInTelangana.add("Swarna");
		damsInTelangana.add("Taliperu");
		damsInTelangana.add("Upper Manair");
		damsInTelangana.add("Vattivagu");
		damsInTelangana.add("Vemular");
		damsInTelangana.add("Wyra");
		damsInTelangana.add("Yellur");
		damsInTelangana.add("Yenukunta");
		damsInTelangana.add("Yerravagu");
		damsInTelangana.add("Zildartippa");
		System.out.println("Size of dams in Telangana : "+damsInTelangana.size());
		
		Collection<String> damsInGoa = new ArrayList<String>();
		damsInGoa.add("Anjunam");
		damsInGoa.add("M.I.");
		damsInGoa.add("Salaulim");
		System.out.println("Size of dams in Goa : "+damsInGoa.size());
		
		Collection<String> damsInGujarat = new ArrayList<String>();
		damsInGujarat.add("Aamli Chharchhoda");
		damsInGujarat.add("Abhalwad");
		damsInGujarat.add("Adhia");
		damsInGujarat.add("Adhochhani");
		damsInGujarat.add("Adhoi- I");
		damsInGujarat.add("Adpur");
		damsInGujarat.add("Advana");
		damsInGujarat.add("Aji I");
		damsInGujarat.add("Aji II");
		damsInGujarat.add("Aji III");
		damsInGujarat.add("Aji IV");
		damsInGujarat.add("Ajwa");
		damsInGujarat.add("Alan Sagar");
		damsInGujarat.add("Amalwant");
		damsInGujarat.add("Ambajal");
		damsInGujarat.add("Ambani Khodiar");
		damsInGujarat.add("Ambaradi");
		damsInGujarat.add("Bagad");
		damsInGujarat.add("Badi-Padva");
		damsInGujarat.add("Bandhara");
		damsInGujarat.add("Dantiwada");
		damsInGujarat.add("Kadana");
		damsInGujarat.add("Kakari Mahudi");
		damsInGujarat.add("Kelia");
		damsInGujarat.add("Khambhala");
		damsInGujarat.add("Mamuara");
		damsInGujarat.add("Mazam");
		damsInGujarat.add("Megal Tr");
		damsInGujarat.add("Meshwo");
		damsInGujarat.add("Mevasa");
		damsInGujarat.add("Mitti");
		damsInGujarat.add("Moj");
		damsInGujarat.add("Nara");
		damsInGujarat.add("Nyari- I");
		damsInGujarat.add("Panam");
		damsInGujarat.add("Sabarmati");
		damsInGujarat.add("Sardar Sarover Gujarat");
		damsInGujarat.add("Shetrunji");
		damsInGujarat.add("Sukhbhadar");
		damsInGujarat.add("Surajwadi");
		damsInGujarat.add("Ukai");
		damsInGujarat.add("Uben");
		damsInGujarat.add("Turkha");
		damsInGujarat.add("Zinzari");
		damsInGujarat.add("sardar sarover saddle");
		damsInGujarat.add("shell Dedumaal");
		damsInGujarat.add("Zar");
		damsInGujarat.add("Zanzarwa");
		damsInGujarat.add("Zalu");
		damsInGujarat.add("Zakashiya");
		damsInGujarat.add("Watrak");
		damsInGujarat.add("Wanklaeswar-Bhey");
		damsInGujarat.add("Wandh-Mandvi");
		damsInGujarat.add("Wandh");
		damsInGujarat.add("Wadhwan Jojwa");
		damsInGujarat.add("Vrajmi");
		damsInGujarat.add("Virpur");
		damsInGujarat.add("Virani");
		damsInGujarat.add("Vijaysagar");
		damsInGujarat.add("Vijarkhi");
		damsInGujarat.add("Veri");
		damsInGujarat.add("Ver II");
		damsInGujarat.add("Veradi -II");
		damsInGujarat.add("Vali");
		damsInGujarat.add("Valavad");
		damsInGujarat.add("Vanala");
		damsInGujarat.add("Vansiali");
		damsInGujarat.add("Vagadi");
		damsInGujarat.add("Vagas");
		damsInGujarat.add("Vagdokyari");
		damsInGujarat.add("Vaghvadarada");
		damsInGujarat.add("Vaidy");
		damsInGujarat.add("Thoralia Mi");
		damsInGujarat.add("Toda");
		damsInGujarat.add("Trivni-Tranga");
		damsInGujarat.add("Thikariyala");
		damsInGujarat.add("Thol");
		damsInGujarat.add("Tara-Manjal");
		damsInGujarat.add("Targol ");
		damsInGujarat.add("Thanagalol");
		damsInGujarat.add("Tharawada");
		damsInGujarat.add("Sod Vadar");
		damsInGujarat.add("Sogth");
		damsInGujarat.add("Solsandha");
		damsInGujarat.add("Sonmati");
		damsInGujarat.add("Sonwadi");
		damsInGujarat.add("Shiney");
		damsInGujarat.add("Shingoda");
		damsInGujarat.add("Shivlakha");
		damsInGujarat.add("Sidhumber");
		damsInGujarat.add("Singla");
		damsInGujarat.add("Singor");
		damsInGujarat.add("Rojki");
		damsInGujarat.add("Rudramata");
		System.out.println("Size of dams in Gujarat : "+damsInGujarat.size());
		
		Collection<String> damsInChhattisgarh = new ArrayList<String>();
		damsInChhattisgarh.add("Tandula");
		damsInChhattisgarh.add("Dudhawa");
		damsInChhattisgarh.add("Gangrel");
		damsInChhattisgarh.add("Kherkatta Reservoir");
		damsInChhattisgarh.add("Murrum Silli");
		damsInChhattisgarh.add("Sondur");
		damsInChhattisgarh.add("Hasdeo Bango");
		damsInChhattisgarh.add("Adpather");
		damsInChhattisgarh.add("Agariya");
		damsInChhattisgarh.add("Ajabnagar");
		damsInChhattisgarh.add("Usaritola");
		damsInChhattisgarh.add("Tanjara");
		damsInChhattisgarh.add("Thakurdiya");
		damsInChhattisgarh.add("Tungal");
		System.out.println("Size of dams in Chhattisgarh : "+damsInChhattisgarh.size());
		
		Collection<String> damsInJammuKashmir = new ArrayList<String>();
		damsInJammuKashmir.add("Baglihar");
		damsInJammuKashmir.add("Dulhasti");
		damsInJammuKashmir.add("Kishenganga");
		damsInJammuKashmir.add("Nimoo Bazgo ");
		damsInJammuKashmir.add("Niu Karewa Storage Yusmarg");
		damsInJammuKashmir.add("Pakal Dul");
		damsInJammuKashmir.add("Salal");
		damsInJammuKashmir.add("Sewa St II");
		damsInJammuKashmir.add("Uri-II");
		System.out.println("Size of dams in Jammu Kashmir : "+damsInJammuKashmir.size());

		Collection<String> damsInHimachalPradesh = new ArrayList<String>();
		damsInHimachalPradesh.add("Baira Siul");
		damsInHimachalPradesh.add("Bassi");
		damsInHimachalPradesh.add("Bhakra");
		damsInHimachalPradesh.add("Chamera I");
		damsInHimachalPradesh.add("Chamera II");
		damsInHimachalPradesh.add("Chamera III ");
		damsInHimachalPradesh.add("Karchham-Wangtoo");
		damsInHimachalPradesh.add("Kol");
		damsInHimachalPradesh.add("Largi");
		damsInHimachalPradesh.add("Malana I");
		damsInHimachalPradesh.add("Nathpa Jhakri");
		damsInHimachalPradesh.add("Pandoh");
		damsInHimachalPradesh.add("Parbati - III");
		damsInHimachalPradesh.add("Parbati II");
		damsInHimachalPradesh.add("Pong");
		damsInHimachalPradesh.add("Sawra- Kuddu");
		System.out.println("Size of dams in Himachal Pradesh : "+damsInHimachalPradesh.size());

		Collection<String> damsInPunjab = new ArrayList<String>();
		damsInPunjab.add("Chohal");
		damsInPunjab.add("Damsal");
		damsInPunjab.add("Dholbaha");
		damsInPunjab.add("Jainti");
		damsInPunjab.add("Janauri");
		damsInPunjab.add("Maili");
		damsInPunjab.add("Mirzapur");
		damsInPunjab.add("Patiari");
		damsInPunjab.add("Perch");
		damsInPunjab.add("Ranjit Sagar");
		damsInPunjab.add("Saleran");
		damsInPunjab.add("Shahpur Kandi");
		damsInPunjab.add("Siswan");
		damsInPunjab.add("Thana");
		System.out.println("Size of dams in Punjab : "+damsInPunjab.size());

		Collection<String> damsInHaryana = new ArrayList<String>();
		damsInHaryana.add("kaushalya");
		System.out.println("Size of dams in Haryana : "+damsInHaryana.size());

		Collection<String> damsInUttarakhand = new ArrayList<String>();
		damsInUttarakhand.add("Baigul");
		damsInUttarakhand.add("Baur");
		damsInUttarakhand.add("Bhimtal");
		damsInUttarakhand.add("Dhauliganga");
		damsInUttarakhand.add("Dhora");
		damsInUttarakhand.add("Haripura");
		damsInUttarakhand.add("Ichari");
		damsInUttarakhand.add("Jamrani");
		damsInUttarakhand.add("Koteshwar");
		damsInUttarakhand.add("Lakhwar");
		damsInUttarakhand.add("Maneri");
		damsInUttarakhand.add("Nanak Sagar");
		damsInUttarakhand.add("Ramganga");
		damsInUttarakhand.add("Tehri");
		damsInUttarakhand.add("Tumaria");
		System.out.println("Size of dams in Uttarakhand : "+damsInUttarakhand.size());
		
		Collection<String>damsInMaharashtra=new ArrayList<String>();
		damsInMaharashtra.add("Dhampur");
		damsInMaharashtra.add("Vihar");
		damsInMaharashtra.add("Ekrukh");
		damsInMaharashtra.add("Shirsufal");
		damsInMaharashtra.add("Tulshi");
		damsInMaharashtra.add("Khadakwasla");
		damsInMaharashtra.add("Ashti");
		damsInMaharashtra.add("Mhaswad");
		damsInMaharashtra.add("Tansa");
		damsInMaharashtra.add("Shetfal");
		damsInMaharashtra.add("Khairbandha");
		damsInMaharashtra.add("Pahari");
		damsInMaharashtra.add("Rhankapur");
		damsInMaharashtra.add("Ramtek");
		damsInMaharashtra.add("Chandapur");
		damsInMaharashtra.add("Walwan");
		damsInMaharashtra.add("Darna");
		damsInMaharashtra.add("Bodalkasa");
		damsInMaharashtra.add("Psolamendha");
		damsInMaharashtra.add("Shirvata");
		damsInMaharashtra.add("Thokarwadi");
		damsInMaharashtra.add("Chokramara");
		damsInMaharashtra.add("Ghorazari");
		damsInMaharashtra.add("Bhandardara");
		damsInMaharashtra.add("Bhatghar");
		damsInMaharashtra.add("Mulshi");
		damsInMaharashtra.add("Mas");
		damsInMaharashtra.add("Ghanewadi");
		damsInMaharashtra.add("Visapur");
		damsInMaharashtra.add("Radhanagari");
		damsInMaharashtra.add("Vaitarna");
		damsInMaharashtra.add("Purmepeda");
		damsInMaharashtra.add("Khasapur");
		damsInMaharashtra.add("Dheku");
		damsInMaharashtra.add("Sindhapan");
		damsInMaharashtra.add("Ekburji");
		damsInMaharashtra.add("Khelocala");
		damsInMaharashtra.add("UpperDudhana");
		damsInMaharashtra.add("Koyna");
		damsInMaharashtra.add("Ganagapur");
		damsInMaharashtra.add("Chandani");
		damsInMaharashtra.add("Bor");
		damsInMaharashtra.add("Ghod");
		damsInMaharashtra.add("Tisangi");
		damsInMaharashtra.add("Wunna");
		damsInMaharashtra.add("Galhati");
		damsInMaharashtra.add("Mangi");
		damsInMaharashtra.add("Mehakari");
		damsInMaharashtra.add("Wan");
		damsInMaharashtra.add("Bhudihal");
		damsInMaharashtra.add("Nawegaonbandh");
		damsInMaharashtra.add("PandherBodi");
		damsInMaharashtra.add("Kurje");
		damsInMaharashtra.add("Nalganga");
		damsInMaharashtra.add("Anjani");
		damsInMaharashtra.add("Siddeshwar");
		damsInMaharashtra.add("Kundrala");
		damsInMaharashtra.add("Gharni");
		damsInMaharashtra.add("Dolwahal");
		damsInMaharashtra.add("Girna");
		damsInMaharashtra.add("Malangaon");
		damsInMaharashtra.add("Karwand");
		damsInMaharashtra.add("Itiadoh");
		damsInMaharashtra.add("Sirpur");
		damsInMaharashtra.add("Pujaritola");
		damsInMaharashtra.add("Terna");
		damsInMaharashtra.add("Morna");
		damsInMaharashtra.add("Gyanganga");
		damsInMaharashtra.add("UpperPus");
		damsInMaharashtra.add("Malkhed");
		damsInMaharashtra.add("Mula");
		damsInMaharashtra.add("UpperVaitarna");
		damsInMaharashtra.add("Panzara");
		damsInMaharashtra.add("Dina");
		damsInMaharashtra.add("Kanoli");
		damsInMaharashtra.add("Nazare");
		damsInMaharashtra.add("Tiru");
		damsInMaharashtra.add("Dhom");
		System.out.println("Size of dams in Maharashtra : "+damsInMaharashtra.size());
		
		Collection<String>damsInMadhyaPradesh=new ArrayList<String>();
		damsInMadhyaPradesh.add("GandhiSagar");
		damsInMadhyaPradesh.add("IndiraSagar");
		damsInMadhyaPradesh.add("BhakraNangal");
		damsInMadhyaPradesh.add("Bansagar");
		damsInMadhyaPradesh.add("Bargi");
		damsInMadhyaPradesh.add("Tehri");
		damsInMadhyaPradesh.add("Barna");
		damsInMadhyaPradesh.add("Tawa");
		damsInMadhyaPradesh.add("Rajghat");
		damsInMadhyaPradesh.add("Idukki");
		damsInMadhyaPradesh.add("NahapaJakhri");
		damsInMadhyaPradesh.add("Omkareshwar");
		damsInMadhyaPradesh.add("Khadalkwasla");
		damsInMadhyaPradesh.add("Mulshi");
		damsInMadhyaPradesh.add("Rihand");
		damsInMadhyaPradesh.add("Ujani");
		damsInMadhyaPradesh.add("Malampuzha");
		damsInMadhyaPradesh.add("Kundala");
		damsInMadhyaPradesh.add("DumkharHydroeElectric");
		damsInMadhyaPradesh.add("Cheruthoni");
		damsInMadhyaPradesh.add("Madikheda");
		damsInMadhyaPradesh.add("Pawna");
		damsInMadhyaPradesh.add("Gangapur");
		damsInMadhyaPradesh.add("BhadBhada");
		damsInMadhyaPradesh.add("Bheemgarh");
		damsInMadhyaPradesh.add("Dhuty");
		damsInMadhyaPradesh.add("Kutni");
		System.out.println("Size of dams in Madhya Pradesh : "+damsInMadhyaPradesh.size());
		
		Collection<String>damsInRajastan=new ArrayList<String>();
		damsInRajastan.add("Bisalpur");
		damsInRajastan.add("JawaharSagar");
		damsInRajastan.add("RanaPratapSagar");
		damsInRajastan.add("Jakham");
		damsInRajastan.add("Jawai");
		damsInRajastan.add("MahiBajajSagar");
		damsInRajastan.add("Tehri");
		damsInRajastan.add("Cheruthoni");
		damsInRajastan.add("KotaBarrage");
		damsInRajastan.add("Gosunda");
		damsInRajastan.add("Sei");
		damsInRajastan.add("SarjuSagr");
		damsInRajastan.add("MansiWakal");
		damsInRajastan.add("Isarda");
		damsInRajastan.add("Jaggar");
		damsInRajastan.add("Kalisindh");
		damsInRajastan.add("Khandip");
		damsInRajastan.add("Morel");
		damsInRajastan.add("Nevta");
		damsInRajastan.add("Parban");
		System.out.println("Size of dams in Rajastan : "+damsInRajastan.size());
		
		Collection<String> damsInUttarPradesh=new ArrayList<String>();
		damsInUttarPradesh.add("Adwa");
		damsInUttarPradesh.add("Afzalgarh ");
		damsInUttarPradesh.add("Ahraura ");
		damsInUttarPradesh.add("Arjun");
		damsInUttarPradesh.add("Aunjhar");
		damsInUttarPradesh.add("Bachara ");
		damsInUttarPradesh.add("Baghel Khand");
		damsInUttarPradesh.add("Baghla ");
		damsInUttarPradesh.add("Balui");
		damsInUttarPradesh.add("Balui");
		damsInUttarPradesh.add("Banjari Kalan");
		damsInUttarPradesh.add("Barwa");
		damsInUttarPradesh.add("Barwa Sagar");
		damsInUttarPradesh.add("Barwar");
		damsInUttarPradesh.add("Barwatola");
		damsInUttarPradesh.add("Bhagwan Pur");
		damsInUttarPradesh.add("Bhainsora");
		damsInUttarPradesh.add("Bhonka");
		damsInUttarPradesh.add("Chandra Prabha");
		damsInUttarPradesh.add("Chandrawal");
		damsInUttarPradesh.add("Chittaurgarh");
		damsInUttarPradesh.add("Deori");
		damsInUttarPradesh.add("Dhandhraul");
		damsInUttarPradesh.add("Dhenkwan");
		damsInUttarPradesh.add("Dongia");
		damsInUttarPradesh.add("Dongri");
		damsInUttarPradesh.add("Ganeshpur");
		damsInUttarPradesh.add("Garhwa");
		damsInUttarPradesh.add("Ghooga");
		damsInUttarPradesh.add("Ghori");
		damsInUttarPradesh.add("Girgity");
		damsInUttarPradesh.add("Gointha");
		damsInUttarPradesh.add("Govind Sagar");
		damsInUttarPradesh.add("Gularia");
		damsInUttarPradesh.add("Gunta");
		damsInUttarPradesh.add("Hinauti");
		damsInUttarPradesh.add("Jaiwanti");
		damsInUttarPradesh.add("Jamini");
		damsInUttarPradesh.add("Jirgo");
		damsInUttarPradesh.add("Jogendra");
		damsInUttarPradesh.add("Kabrai");
		damsInUttarPradesh.add("Kachnoda");
		damsInUttarPradesh.add("Kargara");
		damsInUttarPradesh.add("Keolari");
		damsInUttarPradesh.add("Khairman");
		damsInUttarPradesh.add("Khandeha");
		damsInUttarPradesh.add("Khapatia");
		damsInUttarPradesh.add("Khirihata");
		damsInUttarPradesh.add("Kohar Gaddi");
		damsInUttarPradesh.add("Kota");
		damsInUttarPradesh.add("Kotra Khambha");
		damsInUttarPradesh.add("Kuba Khurd");
		damsInUttarPradesh.add("Lachura");
		damsInUttarPradesh.add("Lower Khajuri");
		damsInUttarPradesh.add("Majhgawan");
		damsInUttarPradesh.add("Matatila");
		damsInUttarPradesh.add("Maudaha");
		damsInUttarPradesh.add("Meja");
		damsInUttarPradesh.add("Moosakhand");
		damsInUttarPradesh.add("Muirpur");
		damsInUttarPradesh.add("Murtia");
		damsInUttarPradesh.add("Nagwa");
		damsInUttarPradesh.add("Nanauti");
		damsInUttarPradesh.add("Narson");
		damsInUttarPradesh.add("Naugarh");
		damsInUttarPradesh.add("Newari");
		damsInUttarPradesh.add("Obra");
		damsInUttarPradesh.add("Ohen");
		damsInUttarPradesh.add("Pachwara Lake");
		damsInUttarPradesh.add("Pahari");
		damsInUttarPradesh.add("Pahuj");
		damsInUttarPradesh.add("Patharai");
		damsInUttarPradesh.add("Pili");
		damsInUttarPradesh.add("Ragura");
		damsInUttarPradesh.add("Raipura");
		damsInUttarPradesh.add("Rajghat");
		damsInUttarPradesh.add("Rajkhar");
		damsInUttarPradesh.add("Rampur");
		damsInUttarPradesh.add("Rampur Kalyangarh");
		damsInUttarPradesh.add("Rampur Pindaria");
		damsInUttarPradesh.add("Rihand");
		damsInUttarPradesh.add("Rohini");
		damsInUttarPradesh.add("Sajnam");
		damsInUttarPradesh.add("Saktesh Garh");
		damsInUttarPradesh.add("Salarpur");
		damsInUttarPradesh.add("Saprar");
		damsInUttarPradesh.add("Sarai Garh");
		damsInUttarPradesh.add("Sarda Sagar");
		damsInUttarPradesh.add("Semri");
		damsInUttarPradesh.add("Shahjad");
		damsInUttarPradesh.add("Siori Lake");
		damsInUttarPradesh.add("Sirsi");
		damsInUttarPradesh.add("Sukhra");
		damsInUttarPradesh.add("Suswar");
		damsInUttarPradesh.add("Upper Khajuri");
		damsInUttarPradesh.add("Urmil");
		damsInUttarPradesh.add("Vijaipur");
		System.out.println("Size of dams in Uttar Pradesh : "+damsInUttarPradesh.size());
		
		Collection<String> damsInIndia = new ArrayList<String>();
		damsInIndia.addAll(damsInJammuKashmir);
		damsInIndia.addAll(damsInHimachalPradesh);
		damsInIndia.addAll(damsInPunjab);
		damsInIndia.addAll(damsInHaryana);
		damsInIndia.addAll(damsInUttarakhand);
		damsInIndia.addAll(damsInGujarat);
		damsInIndia.addAll(damsInKarnataka);
		damsInIndia.addAll(damsInKerala);
		damsInIndia.addAll(damsInGoa);
		damsInIndia.addAll(damsInTamilNadu);
		damsInIndia.addAll(damsInTelangana);
		damsInIndia.addAll(damsInChhattisgarh);
		damsInIndia.addAll(damsInArunachalPradesh);
		damsInIndia.addAll(damsInNagaland);
		damsInIndia.addAll(damsInManipur);
		damsInIndia.addAll(damsInMizoram);
		damsInIndia.addAll(damsInAssam);
		damsInIndia.addAll(damsInMeghalaya);
		damsInIndia.addAll(damsInTripura);
		damsInIndia.addAll(damsInWestBengal);
		damsInIndia.addAll(damsInSikkim);
		damsInIndia.addAll(damsInBihar);
		damsInIndia.addAll(damsInJharkhand);
		damsInIndia.addAll(damsInOdisha);
		damsInIndia.addAll(damsInMaharashtra);
		damsInIndia.addAll(damsInMadhyaPradesh);
		damsInIndia.addAll(damsInRajastan);
		damsInIndia.addAll(damsInUttarPradesh);
		
		Iterator<String> itr = damsInIndia.iterator();
		while (itr.hasNext()) {
			String element =itr.next();
			if (element.startsWith("T")) {
				System.out.println(element);
			}
		}

		Iterator<String> itr1 = damsInIndia.iterator();
		while (itr1.hasNext()) {
			String element1 = itr1.next();
			if (element1.endsWith("ra")) {
				System.out.println(element1);
			}
		}

		Iterator<String> itr2 = damsInIndia.iterator();
		while (itr2.hasNext()) {
			String element2 = itr2.next();
			if (element2.length() > 15) {
				System.out.println(element2);
			}
		}

		Iterator<String> itr3 = damsInIndia.iterator();
		while (itr3.hasNext()) {
			String element3 = itr3.next();
			System.out.println(element3.toUpperCase());
		}
		
		
		Iterator itr4 = damsInIndia.iterator();
		while (itr4.hasNext()) {
			String element4 = (String) itr4.next();
			System.out.println(element4.toLowerCase());
		}
		
		Iterator<String> length=damsInIndia.iterator();
		while(length.hasNext()) {
			String element=length.next();
			if(element.length()>=15) {
				System.out.println("element length greater than 15 characters"+element);
			}
		}
		
		Iterator<String> remove = damsInIndia.iterator();
		while (remove.hasNext()) {
			String element = remove.next();
			if (element.contains("P"))
				System.out.println("Removing all dams it contains P " + element);
			remove.remove();
		}

		Iterator palindrome = damsInIndia.iterator();
		while (palindrome.hasNext()) {
			String element = (String) palindrome.next();
			StringBuffer buffer = new StringBuffer(element);
			buffer.reverse();
			String reverse = buffer.toString();
			if (element.equalsIgnoreCase(reverse)) {
				System.err.println("Palindrome " + reverse);
			}
		}
			
	}

}
