package com.xworkz.copy.example.boot;

import java.awt.AWTException;
import java.awt.FontFormatException;
import java.awt.datatransfer.MimeTypeParseException;
import java.awt.print.PrinterException;
import java.beans.IntrospectionException;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.lang.instrument.IllegalClassFormatException;
import java.nio.channels.AlreadyBoundException;
import java.rmi.MarshalException;
import java.rmi.activation.ActivationException;
import java.security.GeneralSecurityException;
import java.security.acl.AclNotFoundException;
import java.security.acl.NotOwnerException;
import java.security.cert.CertificateException;
import java.text.ParseException;
import java.util.concurrent.BrokenBarrierException;
import java.util.zip.DataFormatException;

import javax.management.BadStringOperationException;
import javax.management.InvalidApplicationException;
import javax.management.JMException;
import javax.management.modelmbean.InvalidTargetObjectTypeException;
import javax.naming.NamingException;
import javax.security.auth.DestroyFailedException;
import javax.security.auth.RefreshFailedException;
import javax.sound.midi.InvalidMidiDataException;
import javax.sound.midi.MidiUnavailableException;
import javax.swing.text.BadLocationException;
import javax.swing.tree.ExpandVetoException;
import javax.xml.datatype.DatatypeConfigurationException;
import javax.xml.parsers.ParserConfigurationException;

import org.ietf.jgss.GSSException;
import org.omg.CORBA.portable.ApplicationException;

import com.xworkz.copy.example.ExceptionProgram;

public class ExceptionProgramRunner {

	public static void main(String[] args) throws AclNotFoundException,ActivationException,AlreadyBoundException,ApplicationException,AWTException,BadLocationException,BadStringOperationException,BrokenBarrierException,CertificateException,CloneNotSupportedException,DataFormatException,DatatypeConfigurationException,DestroyFailedException,ExpandVetoException,FontFormatException,GeneralSecurityException,GSSException,IllegalClassFormatException,IntrospectionException,InvalidApplicationException,InvalidMidiDataException,InvalidTargetObjectTypeException,IOException,MarshalException,JMException,MidiUnavailableException,MimeTypeParseException,NamingException,NotOwnerException,ParseException,ParserConfigurationException,PrinterException,PropertyVetoException,ReflectiveOperationException,RefreshFailedException{

		ExceptionProgram program=new ExceptionProgram();
		program.runTimeExceptionMethod1();
		program.runTimeExceptionMethod2();
		program.runTimeExceptionMethod3();
		program.runTimeExceptionMethod4();
		program.runTimeExceptionMethod5();
		program.runTimeExceptionMethod6();
		program.runTimeExceptionMethod7();
		program.runTimeExceptionMethod8();
		program.runTimeExceptionMethod9();
		program.runTimeExceptionMethod10();
		program.runTimeExceptionMethod11();
		program.runTimeExceptionMethod12();
		program.runTimeExceptionMethod13();
		program.runTimeExceptionMethod14();
		program.runTimeExceptionMethod15();
		program.runTimeExceptionMethod16();
		program.runTimeExceptionMethod17();
		program.runTimeExceptionMethod18();
		program.runTimeExceptionMethod19();
		program.runTimeExceptionMethod20();
		program.runTimeExceptionMethod21();
		program.runTimeExceptionMethod22();
		program.runTimeExceptionMethod23();
		program.runTimeExceptionMethod24();
		program.runTimeExceptionMethod25();
		program.runTimeExceptionMethod26();
		program.runTimeExceptionMethod27();
		program.runTimeExceptionMethod28();
		program.runTimeExceptionMethod29();
		program.runTimeExceptionMethod30();
		program.runTimeExceptionMethod31();
		program.runTimeExceptionMethod32();
		program.runTimeExceptionMethod33();
		program.runTimeExceptionMethod34();
		program.runTimeExceptionMethod35();
		program.ExceptionMethod1();
		program.ExceptionMethod2();
		program.ExceptionMethod3();
		program.ExceptionMethod4();
		program.ExceptionMethod5();
		program.ExceptionMethod6();
		program.ExceptionMethod7();
		program.ExceptionMethod8();
		program.ExceptionMethod9();
		program.ExceptionMethod10();
		program.ExceptionMethod11();
		program.ExceptionMethod12();
		program.ExceptionMethod13();
		program.ExceptionMethod14();
		program.ExceptionMethod15();
		program.ExceptionMethod16();
		program.ExceptionMethod17();
		program.ExceptionMethod18();
		program.ExceptionMethod19();
		program.ExceptionMethod20();
		program.ExceptionMethod21();
		program.ExceptionMethod22();
		program.ExceptionMethod23();
		program.ExceptionMethod24();
		program.ExceptionMethod25();
		program.ExceptionMethod26();
		program.ExceptionMethod27();
		program.ExceptionMethod28();
		program.ExceptionMethod29();
		program.ExceptionMethod30();
		program.ExceptionMethod31();
		program.ExceptionMethod32();
		program.ExceptionMethod33();
		program.ExceptionMethod34();
		program.ExceptionMethod35();
		program.ErrorMethod1();
		program.ErrorMethod2();
		program.ErrorMethod3();
		program.ErrorMethod4();
		program.ErrorMethod5();
		program.ErrorMethod6();
		program.ErrorMethod7();
		program.ErrorMethod8();
		program.ErrorMethod9();
		program.ErrorMethod10();
		program.ErrorMethod11();
		program.ErrorMethod12();
		program.ErrorMethod13();
		program.ErrorMethod14();
		program.ErrorMethod15();
		program.ErrorMethod16();
		program.ErrorMethod17();
		program.ErrorMethod18();
		program.ErrorMethod19();
		program.ErrorMethod20();
		program.ErrorMethod21();
		program.ErrorMethod22();
		program.ErrorMethod23();
		program.ErrorMethod24();
		program.ErrorMethod25();
		program.ErrorMethod26();
		program.ErrorMethod27();
		program.ErrorMethod28();
		program.ErrorMethod29();
		program.ErrorMethod30();
		
		
	}

}
